name: pigeon
description: Code generator tool to make communication between Flutter and the host platform type-safe and easier.
repository: https://github.com/flutter/packages/tree/main/packages/pigeon
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3Apigeon
version: 11.0.1 # This must match the version in lib/generator_tools.dart

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  analyzer: "^6.2.0"
  args: ^2.4.2
  collection: ^1.17.2
  meta: ^1.9.1
  path: ^1.8.3
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.11.1

topics:
  - codegen
  - interop
  - platform-channels
  - plugin-development
